# Generated by Django 4.0 on 2022-09-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_id_product_proudctid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='proudctId',
            new_name='id',
        ),
    ]
