# Generated by Django 4.0 on 2023-01-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_seller_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images')),
            ],
        ),
    ]
